export const APPWRITE_URL = import.meta.env.VITE_REACT_APP_APPWRITE_URL;
export const APPWRITE_PROJECT_ID = import.meta.env
  .VITE_REACT_APP_APPWRITE_PROJECT_ID;
export const APPWRITE_DATABASE_ID = import.meta.env
  .VITE_REACT_APP_APPWRITE_DATABASE_ID;
export const APPWRITE_COLLECTION_ID = import.meta.env
  .VITE_REACT_APP_APPWRITE_COLLECTION_ID;
export const APPWRITE_BUCKET_ID = import.meta.env
  .VITE_REACT_APP_APPWRITE_BUCKET_ID;
